minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "axios@1.16.0"
preferFrozenLockfile: true
engineStrict: true
strictDepBuilds: true
blockExoticSubdeps: true
overrides:
  "ajv": "^6.14.0"
  "axios": "^1.15.2"
  "brace-expansion": "^2.0.3"
  "braces": "^3.0.3"
  "cross-spawn": "^7.0.5"
  "ejs": "^3.1.10"
  "flatted": "^3.4.2"
  "follow-redirects": "^1.16.0"
  "glob": "^11.1.0"
  "immutable": "^5.1.5"
  "js-yaml": "^4.1.1"
  "lodash.trim": "4.18.0"
  "lodash.trimend": "4.18.0"
  "micromatch": "^4.0.8"
  "minimatch": "^5.1.8"
  "@oclif/core@4.10.3>minimatch": "^10.2.4"
  "@oclif/core@4.5.5>minimatch": "^9.0.5"
  "glob@11.1.0>minimatch": "^10.1.1"
  "picomatch": "^2.3.2"
  "semver": "^7.5.2"
  "tmp@<=0.2.3": "^0.2.4"
  "undici": "^7.24.0"
  "word-wrap": "^1.2.4"
  "yaml": "^2.8.3"
