minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "axios@1.16.0"
  - "form-data@4.0.6"
preferFrozenLockfile: true
engineStrict: true
strictDepBuilds: true
blockExoticSubdeps: true
overrides:
  "ajv@<6.14.0": "^6.14.0"
  "axios@<1.15.2": "^1.15.2"
  "brace-expansion@<2.0.3": "^2.0.3"
  "braces@<3.0.3": "^3.0.3"
  "cross-spawn@<7.0.5": "^7.0.5"
  "ejs@<3.1.10": "^3.1.10"
  "flatted@<3.4.2": "^3.4.2"
  "follow-redirects@<1.16.0": "^1.16.0"
  "form-data@>=4.0.0 <4.0.6": "^4.0.6"
  "glob@<11.1.0": "^11.1.0"
  "immutable@<5.1.5": "^5.1.5"
  "js-yaml@<=4.1.1": "^4.2.0"
  "lodash.trim@<4.18.0": "4.18.0"
  "lodash.trimend@<4.18.0": "4.18.0"
  "micromatch@<4.0.8": "^4.0.8"
  "minimatch@<5.1.8": "^5.1.8"
  "@oclif/core@>=4.10.3 <4.10.4>minimatch": "^10.2.4"
  "@oclif/core@>=4.5.5 <4.5.6>minimatch": "^9.0.5"
  "glob@>=11.1.0 <11.1.1>minimatch": "^10.1.1"
  "picomatch@<2.3.2": "^2.3.2"
  "semver@<7.5.2": "^7.5.2"
  "tmp@<0.2.6": "^0.2.6"
  "undici@<7.24.0": "^7.24.0"
  "uuid@<11.1.1": "^11.1.1"
  "ws@>=7.0.0 <7.5.11": "^7.5.11"
  "word-wrap@<1.2.4": "^1.2.4"
  "yaml@<2.8.3": "^2.8.3"
